name: Terraform Plan Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    # 1. הורדת הקוד מה-Repository
    - name: Checkout
      uses: actions/checkout@v3

    # 2. התקנת Terraform על המחשב המרוחק של GitHub
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 3. אתחול (בדיקה שהקבצים תקינים)
    - name: Terraform Init
      run: terraform init
      working-directory: ./terrraform # ודא שזה השם המדויק של התיקייה אצלך

    # 4. בדיקת פורמט (לוודא שהקוד כתוב יפה)
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terrraform

    # 5. הרצת ה-Plan (השלב החשוב ביותר)
    # כאן ה-Pipeline רק יגיד מה הוא היה עושה, בלי לבצע בפועל
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terrraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # שנו לאזור שלכם